### ISSUE TITLE
ABB Quaternion are in scalar first or vector first representation?

### ISSUE THREAD

**Issue by amanabt** [miguelrasteiro/IMU_dataset#1]
Hi,

I have just started using this wonderful dataset to test an extended kalman filter. I want to first animate the ground truth vs time. I have two questions regarding this:

1. Am I correct in assuming that the ground truth is under the key 'ABBposition' and 'ABBquaternion'?
2. Are the quaternions in scalar first format (qw, qx, qy, qz) or vector first (qx, qy, qz, qw) format?

**Comment by hcostelha** [comment]
Hi,

> Hi,
> 
> I have just started using this wonderful dataset to test an extended kalman filter. I want to first animate the ground truth vs time. I have two questions regarding this:
> 
> 1. Am I correct in assuming that the ground truth is under the key 'ABBposition' and 'ABBquaternion'?

Yes, the robot provided values are what we considered our ground-truth.

> 2. Are the quaternions in scalar first format (qw, qx, qy, qz) or vector first (qx, qy, qz, qw) format?

Yes, the quaternions are in scalar first format. You can confirm that by looing at the starting orientations and some parts of the code where we start with "[1 0 0 0]".

**Comment by amanabt** [comment]
Thank you for your prompt response
